spring:
  datasource:
    url: jdbc:mysql://localhost/test-entrevista?allowPublicKeyRetrieval=true&useSSL=false&useTimezone=true&serverTimezone=GMT&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  thymeleaf:
    cache: false

  web:
    resources:
      cache:
        cachecontrol:
          no-cache: false
          no-store: false
          must-revalidate: false
          max-age: 365d   # âœ… forma moderna
    error:
      whitelabel:
        enabled: false
      path: /error

server:
  servlet:
    session:
      timeout: 3600
      cookie:
        http-only: true
      tracking-modes:
        - cookie

session:
  timeout: 3600

base-endpoint:
  value: "http://localhost:8080/"

application:
  traccar:
    host: "http://test"
    port: "8082"
    basePath: "/api"
    username: admin
    password: test2026